package.path = package.path .. ";./?.lua;./?/init.lua"

print("\nSTART UNIT TESTS\n")
require('test.base-components.counter-component')
require('test.base-components.numeric-component')
require('test.base-components.product-component')
require('test.base-components.storage-component')
print()
require('test.base-evaluators.overrider-evaluator')
require('test.base-evaluators.condition-evaluator')
require('test.base-evaluators.parameter-evaluator')
require('test.base-evaluators.reduction-evaluator')
print()
require('test.local-evaluators.local-evaluator')
print()
require('test.modifiers.progressive-modifiers')
require('test.modifiers.conditional-modifiers')
print()